"""Rollout helpers (§12 phases 1–3, appendix B).

Pure text/YAML transformations used by the two rollout scripts. Nothing here talks
to GitLab, so every rule below is unit-tested in ``tests/test_rollout.py``.

Two rules shape the design:

* **We never rewrite a consumer's CI file.** Editing ``.gitlab-ci.yml`` with a YAML
  dumper destroys comments and formatting, so the include block is inserted as text
  and any shape we do not understand is reported for a human instead of guessed at.
* **Drafts are review artefacts.** ``bootstrap_codeowners.py`` writes drafts into a
  directory; a human owns the merge (`--apply` is opt-in in ``rollout.py``).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

import yaml

from .codeowners import parse

#: First top-level ``include:`` key in a CI file, if any.
_INCLUDE_RE = re.compile(r"^include\s*:", re.MULTILINE)

DEFAULT_MARKER = "<!-- ownership-notify:rollout -->"


class RolloutError(Exception):
    """Raised when a file cannot be transformed safely."""


@dataclass
class RepoDraft:
    """One repository's ownership draft."""

    project: str
    default_owner: str = ""
    rules: dict[str, str] = field(default_factory=dict)
    ci_inputs: dict[str, str] = field(default_factory=dict)
    target_branch: str = ""

    @property
    def codeowners_path(self) -> str:
        return ".gitlab/CODEOWNERS"


# --------------------------------------------------------------------- mapping


def load_mapping(text: str, *, source: str = "mapping.yml") -> dict[str, RepoDraft]:
    """Read the rollout mapping: which repository owns what.

    ```yaml
    repositories:
      acme/services/payment-service:
        target_branch: master
        default_owner: "@acme/teams/platform"      # becomes the `*` rule
        rules:
          "src/main/java/com/acme/payments/**": "@acme/teams/payments @alice"
        ci_inputs:
          mode: report                             # phase 2: report before notify
    ```
    """
    data = yaml.safe_load(text) or {}
    if not isinstance(data, dict):
        raise RolloutError(f"{source}: top level must be a mapping")

    raw_repos = data.get("repositories") or {}
    if not isinstance(raw_repos, dict) or not raw_repos:
        raise RolloutError(f"{source}: 'repositories' must be a non-empty mapping")

    drafts: dict[str, RepoDraft] = {}
    for project, raw in raw_repos.items():
        if not isinstance(raw, dict):
            raise RolloutError(f"{source}: repository '{project}' must be a mapping")
        rules = raw.get("rules") or {}
        if not isinstance(rules, dict):
            raise RolloutError(f"{source}: 'rules' of '{project}' must be a mapping")
        drafts[project] = RepoDraft(
            project=project,
            default_owner=str(raw.get("default_owner") or ""),
            rules={str(pattern): " ".join(str(v).split()) for pattern, v in rules.items()},
            ci_inputs={str(k): str(v) for k, v in (raw.get("ci_inputs") or {}).items()},
            target_branch=str(raw.get("target_branch") or ""),
        )
    return drafts


# ------------------------------------------------------------------ CODEOWNERS

_HEADER = """\
# CODEOWNERS for {project}
#
# Generated by scripts/bootstrap_codeowners.py, then owned by hand: GitLab uses the
# **last matching pattern** and pattern order is therefore meaningful.
#
# Rules of the road (docs/design.md §7.1):
#   * `*` does not cross `/`, `**` does.
#   * there is no `!` negation — ignore rules live in teams.yml.
#   * a path matching nothing is *unclaimed* and is reported by the drift report.
"""


def render_codeowners(draft: RepoDraft, *, header: str = _HEADER) -> str:
    """Render a draft CODEOWNERS file for one repository."""
    lines: list[str] = [header.format(project=draft.project).rstrip(), ""]

    if draft.default_owner:
        lines.append("# fallback owner for anything not listed below")
        lines.append(f"* {draft.default_owner}")
        lines.append("")

    section = ""
    for pattern, owners in draft.rules.items():
        if not owners:
            raise RolloutError(f"{draft.project}: pattern '{pattern}' has no owner")
        # Section headers are only cosmetic (`[Name]` groups patterns in the UI),
        # so they are derived from the first owner token to keep the file readable.
        token = owners.split()[0]
        name = _section_name(token)
        if name and name != section:
            section = name
            lines.append(f"[{name}]")
        lines.append(f"{pattern} {owners}")

    if draft.rules:
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _section_name(token: str) -> str:
    if not token.startswith("@"):
        return ""
    return token.rsplit("/", 1)[-1].replace("-", " ").replace("_", " ").title()


def uncovered_prefixes(
    tree_paths: list[str], patterns: dict[str, str], *, depth: int = 3
) -> list[str]:
    """Top-level directories of a repository that no rule (and no fallback) covers.

    This is the list a human has to make a decision about during bootstrap: the files
    GitLab would report as *unclaimed* once the draft is installed (§7.1).
    """
    if any(rule.strip() == "*" for rule in patterns):
        return []

    parsed = parse("\n".join(f"{pattern} @placeholder" for pattern in patterns))
    candidates = {
        "/".join(path.split("/")[:depth])
        for path in tree_paths
        if "/" in path
    }
    return sorted(
        candidate for candidate in candidates if parsed.rule_for(candidate) is None
    )


def validate_codeowners(text: str, *, known_tokens: set[str] | None = None) -> list[str]:
    """Syntax problems, plus owner tokens that no team in teams.yml claims.

    Catches the two mistakes that make a rollout pointless: a line GitLab would
    ignore silently, and an owner token that resolves to nobody.
    """
    parsed = parse(text)
    problems = list(parsed.problems)

    if known_tokens is not None:
        tokens = {token for rule in parsed.rules for token in rule.owners if token.startswith("@")}
        unknown = sorted(tokens - known_tokens)
        if unknown:
            problems.append(f"owner token(s) with no team: {', '.join(unknown)}")

    if not parsed.rules:
        problems.append("no rules at all: every changed file would be unclaimed")

    return problems


# ------------------------------------------------------------------------- CI


def component_include_block(component: str, inputs: dict[str, str] | None = None) -> str:
    """The YAML snippet a consumer adds to ``.gitlab-ci.yml``."""
    lines = ["include:", f"  - component: {component}"]
    if inputs:
        lines.append("    inputs:")
        lines.extend(f"      {key}: {value}" for key, value in inputs.items())
    return "\n".join(lines) + "\n"


def has_include(ci_text: str, component: str) -> bool:
    """True when the component path already appears in the file (bare path match)."""
    return component.split("@", 1)[0] in ci_text


def ensure_include(ci_text: str, component: str, inputs: dict[str, str] | None = None) -> str:
    """Insert the component include, preserving the rest of the file byte for byte.

    Raises :class:`RolloutError` when the file has an ``include:`` whose shape we
    should not touch (an inline scalar or list). The caller reports that instead of
    guessing, so a rollout MR never silently rewrites someone's pipeline.
    """
    if has_include(ci_text, component):
        return ci_text

    entries = component_include_block(component, inputs).splitlines()[1:]
    inserted = "\n".join(entries)

    match = _INCLUDE_RE.search(ci_text)
    if match is None:
        return f"{component_include_block(component, inputs)}\n{ci_text.lstrip()}"

    if ci_text[match.end() : match.end() + 1] not in ("", "\n"):
        raise RolloutError(
            "existing 'include:' is not a block list; add the component include by hand"
        )

    _, _, rest = ci_text[match.end() :].partition("\n")
    remainder = rest.lstrip("\n")
    prefix = f"{ci_text[: match.end()]}\n{inserted}\n"
    return f"{prefix}\n{remainder}" if remainder else prefix

