"""Rollout helpers (§12 phases 1–3, appendix B).

Pure text/YAML transformations used by the two rollout scripts. Nothing here talks
to GitLab, so every rule below is unit-tested in ``tests/test_rollout.py``.

Two rules shape the design:

* **We never rewrite a consumer's CI file.** Editing ``.gitlab-ci.yml`` with a YAML
  dumper destroys comments and formatting, so the include block is inserted as text
  and any shape we do not understand is reported for a human instead of guessed at.
* **Drafts are review artefacts.** ``bootstrap_codeowners.py`` writes drafts into a
  directory; a human owns the merge (`--apply` is opt-in in ``rollout.py``).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

import yaml

from .codeowners import parse

#: First top-level ``include:`` key in a CI file, if any.
_INCLUDE_RE = re.compile(r"^include\s*:", re.MULTILINE)

DEFAULT_MARKER = "<!-- ownership-notify:rollout -->"


class RolloutError(Exception):
    """Raised when a file cannot be transformed safely."""


@dataclass
class RepoDraft:
    """One repository's ownership draft."""

    project: str
    default_owner: str = ""
    rules: dict[str, str] = field(default_factory=dict)
    ci_inputs: dict[str, str] = field(default_factory=dict)
    target_branch: str = ""

    @property
    def codeowners_path(self) -> str:
        return ".gitlab/CODEOWNERS"


# --------------------------------------------------------------------- mapping


def load_mapping(text: str, *, source: str = "mapping.yml") -> dict[str, RepoDraft]:
    """Read the rollout mapping: which repository owns what.

    ```yaml
    repositories:
      acme/services/payment-service:
        target_branch: master
        default_owner: "@acme/teams/platform"      # becomes the `*` rule
        rules:
          "src/main/java/com/acme/payments/**": "@acme/teams/payments @alice"
        ci_inputs:
          mode: report                             # phase 2: report before notify
    ```
    """
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise RolloutError(f"{source}: invalid YAML: {exc}") from exc
    data = data or {}
    if not isinstance(data, dict):
        raise RolloutError(f"{source}: top level must be a mapping")

    raw_repos = data.get("repositories") or {}
    if not isinstance(raw_repos, dict) or not raw_repos:
        raise RolloutError(f"{source}: 'repositories' must be a non-empty mapping")

    drafts: dict[str, RepoDraft] = {}
    for project, raw in raw_repos.items():
        if not isinstance(raw, dict):
            raise RolloutError(f"{source}: repository '{project}' must be a mapping")
        rules = raw.get("rules") or {}
        if not isinstance(rules, dict):
            raise RolloutError(f"{source}: 'rules' of '{project}' must be a mapping")
        drafts[project] = RepoDraft(
            project=project,
            default_owner=str(raw.get("default_owner") or ""),
            rules={str(pattern): " ".join(str(v).split()) for pattern, v in rules.items()},
            ci_inputs={str(k): str(v) for k, v in (raw.get("ci_inputs") or {}).items()},
            target_branch=str(raw.get("target_branch") or ""),
        )
    return drafts


# ------------------------------------------------------------------ CODEOWNERS

_HEADER = """\
# CODEOWNERS for {project}
#
# Generated by scripts/bootstrap_codeowners.py, then owned by hand: GitLab uses the
# **last matching pattern** and pattern order is therefore meaningful.
#
# Rules of the road (docs/design.md §7.1):
#   * `*` does not cross `/`, `**` does.
#   * there is no `!` negation — ignore rules live in teams.yml.
#   * a path matching nothing is *unclaimed* and is reported by the drift report.
"""


def render_codeowners(draft: RepoDraft, *, header: str = _HEADER) -> str:
    """Render a draft CODEOWNERS file for one repository."""
    lines: list[str] = [header.format(project=draft.project).rstrip(), ""]

    if draft.default_owner:
        lines.extend(
            [
                "# fallback owner for anything not listed below",
                f"* {draft.default_owner}",
                "",
            ]
        )

    section = ""
    for pattern, owners in draft.rules.items():
        if not owners:
            raise RolloutError(f"{draft.project}: pattern '{pattern}' has no owner")
        # Section headers are only cosmetic (`[Name]` groups patterns in the UI),
        # so they are derived from the first owner token to keep the file readable.
        token = owners.split()[0]
        name = _section_name(token)
        if name and name != section:
            section = name
            lines.append(f"[{name}]")
        lines.append(f"{pattern} {owners}")

    if draft.rules:
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _section_name(token: str) -> str:
    if not token.startswith("@"):
        return ""
    return token.rsplit("/", 1)[-1].replace("-", " ").replace("_", " ").title()


def uncovered_prefixes(tree_paths: list[str], patterns: dict[str, str], *, depth: int = 3) -> list[str]:
    """Top-level directories of a repository that no rule (and no fallback) covers.

    This is the list a human has to make a decision about during bootstrap: the files
    GitLab would report as *unclaimed* once the draft is installed (§7.1).
    """
    if any(rule.strip() == "*" for rule in patterns):
        return []

    parsed = parse("\n".join(f"{pattern} @placeholder" for pattern in patterns))
    candidates = {"/".join(path.split("/")[:depth]) for path in tree_paths if "/" in path}
    return sorted(candidate for candidate in candidates if parsed.rule_for(candidate) is None)


def validate_codeowners(text: str, *, known_tokens: set[str] | None = None) -> list[str]:
    """Syntax problems, plus owner tokens that no team in teams.yml claims.

    Catches the two mistakes that make a rollout pointless: a line GitLab would
    ignore silently, and an owner token that resolves to nobody.
    """
    parsed = parse(text)
    problems = list(parsed.problems)

    if known_tokens is not None:
        tokens = {token for rule in parsed.rules for token in rule.owners if token.startswith("@")}
        unknown = sorted(tokens - known_tokens)
        if unknown:
            problems.append(f"owner token(s) with no team: {', '.join(unknown)}")

    if not parsed.rules:
        problems.append("no rules at all: every changed file would be unclaimed")

    return problems


# ------------------------------------------------------------------------- CI


def component_include_block(component: str, inputs: dict[str, str] | None = None) -> str:
    """The YAML snippet a consumer adds to ``.gitlab-ci.yml``."""
    lines = ["include:", f"  - component: {component}"]
    if inputs:
        lines.append("    inputs:")
        lines.extend(f"      {key}: {value}" for key, value in inputs.items())
    return "\n".join(lines) + "\n"


def _component_path_line(component: str) -> str:
    return component.split("@", 1)[0]


def has_include(ci_text: str, component: str) -> bool:
    """True when an ``include:`` entry already references this component.

    Matched as a whole YAML mapping rather than a bare substring, so a mention in a
    comment or a similarly named component does not look like an existing include. A
    file that does not parse — ``!reference`` and other custom tags are common in GitLab
    CI — falls back to the conservative substring check, so an include that is already
    present is never duplicated.
    """
    target = _component_path_line(component)
    try:
        data = yaml.safe_load(ci_text)
    except yaml.YAMLError:
        return target in ci_text
    if not isinstance(data, dict):
        return False

    entries = data.get("include")
    if isinstance(entries, dict):
        entries = [entries]
    if not isinstance(entries, list):
        return False

    for entry in entries:
        if isinstance(entry, dict):
            value = entry.get("component")
            if isinstance(value, str) and _component_path_line(value) == target:
                return True
    return False


def _sequence_indent(block: str) -> str | None:
    """Where the first item of a block sequence starts, so we can match it.

    Returns the item's leading whitespace (``""`` at column 0, which YAML allows for a
    sequence under a mapping key). ``""`` also means the block holds no items yet — the
    next line is a sibling key or the block is empty. ``None`` means the block is a
    mapping (or tab-indented), a shape we refuse to rewrite rather than guess at.
    """
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = line[: len(line) - len(line.lstrip(" \t"))]
        if stripped.startswith("-"):
            return None if "\t" in indent else indent
        # A non-item at column 0 is the next top-level key, not part of `include:`.
        return "" if indent == "" else None
    return ""


def _reindent(entries: list[str], indent: str) -> str:
    """Shift the generated entries (based at two spaces) onto ``indent``."""
    return "\n".join(indent + line[2:] if line.startswith("  ") else indent + line for line in entries)


def ensure_include(ci_text: str, component: str, inputs: dict[str, str] | None = None) -> str:
    """Insert the component include, preserving the rest of the file byte for byte.

    Raises :class:`RolloutError` when the file has an ``include:`` whose shape we
    should not touch (an inline scalar, a block mapping, or tab-indented entries). The
    caller reports that instead of guessing, so a rollout MR never silently rewrites
    someone's pipeline.
    """
    if has_include(ci_text, component):
        return ci_text

    # The component path can contain ``@`` but never at the start of the value, so YAML
    # reads `host/path@version` as a plain scalar. No quoting needed.
    include_block = component_include_block(component, inputs)
    entries = include_block.splitlines()[1:]

    match = _INCLUDE_RE.search(ci_text)
    if match is None:
        return f"{include_block}\n{ci_text.lstrip()}"

    if ci_text[match.end() : match.end() + 1] not in ("", "\n"):
        raise RolloutError("existing 'include:' is not a block list; add the component include by hand")

    rest = ci_text[match.end() :].removeprefix("\n")
    indent = _sequence_indent(rest)
    if indent is None:
        raise RolloutError("existing 'include:' is not a block list; add the component include by hand")

    # Match the existing entries' indentation so the merged block reads as one list
    # rather than a sequence whose items are indented inconsistently.
    inserted = _reindent(entries, indent)
    return f"{ci_text[: match.end()]}\n{inserted}\n{rest}"
